# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2

multi-ecosystem-groups:
  dependencies:
    schedule:
      interval: "weekly"

updates:
  # npm (Node.js) dependencies
  - package-ecosystem: "npm"
    directory: "/" # Location of package manifests
    ignore:
      # Using Node.js 22 LTS
      - dependency-name: "@types/node"
        versions: [ ">=22" ]
      # Pin Next.js to latest supported by Cloudflare Workers
      - dependency-name: "next"
        versions: [ ">=15.3.5" ]
      - dependency-name: "eslint-config-next"
        versions: [ ">=15.3.5" ]
      # MCP only works with Zod v3
      - dependency-name: "zod"
        versions: [ ">3" ]
      # @cloudflare/vitest-pool-workers only works with Vitest v3
      - dependency-name: "vitest"
        versions: [ ">3" ]
    patterns: ["*"]
    multi-ecosystem-group: "dependencies"

  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    patterns: ["*"]
    multi-ecosystem-group: "dependencies"
